# Generated by Django 4.2.2 on 2023-07-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_donacion', models.CharField(choices=[('efectivo', 'Donación en efectivo'), ('bonos', 'Donación de bonos'), ('transferencia', 'Transferencia bancaria')], max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
