# Generated by Django 4.2.2 on 2023-07-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('objetivo_general', models.TextField()),
                ('objeto_social', models.TextField()),
                ('objetivos_especificos', models.TextField()),
            ],
        ),
    ]
