# Generated by Django 4.2.1 on 2023-07-02 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion_legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionlegal',
            name='camara_comercio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='informacionlegal',
            name='certificado_esal',
            field=models.FileField(default=None, upload_to='esal_certificates/'),
        ),
        migrations.AddField(
            model_name='informacionlegal',
            name='direccion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='informacionlegal',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='informacionlegal',
            name='fecha_constitucion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='informacionlegal',
            name='registro_dian',
            field=models.CharField(default=datetime.datetime(2023, 7, 2, 20, 21, 44, 295622, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacionlegal',
            name='representante_legal',
            field=models.CharField(default='fulano de tal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacionlegal',
            name='telefono',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
